Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: None
    
AllowedHosts: "*"
JWT:
  Key: "This is a very secret key that i will use to sign my tokens"